# Generated by Django 4.2.19 on 2025-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
    ]
