# Generated by Django 4.2.19 on 2025-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_state_created_by_alter_state_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='designation',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='institute',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='institute',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='CREATED_BY',
            field=models.CharField(db_column='CREATED_BY', default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='UPDATED_BY',
            field=models.CharField(db_column='UPDATED_BY', default='system', max_length=50),
        ),
    ]
