# Generated by Django 4.2.19 on 2025-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_country_created_by_alter_country_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
    ]
