# Generated by Django 4.2.19 on 2025-02-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_branch_deleted_by_alter_category_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='CATEGORY',
        ),
    ]
