# Generated by Django 4.2.19 on 2025-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='IS_ACTIVE',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
    ]
