# Generated by Django 4.2.19 on 2025-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_experience',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_experience',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_experience',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_qualification',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_qualification',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_qualification',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_research',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_research',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_research',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
    ]
