# Generated by Django 4.2.19 on 2025-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_schemas'),  # Make sure this points to your core migration that creates schemas
    ]

    operations = [
        migrations.RunSQL(
            # Create schema first
            'CREATE SCHEMA IF NOT EXISTS "ESTABLISHMENT";'
        ),
        migrations.CreateModel(
            name='SHIFT_MASTER',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('SHIFT_NAME', models.CharField(db_column='SHIFT_NAME', max_length=50)),
                ('FROM_TIME', models.TimeField(db_column='FROM_TIME')),
                ('TO_TIME', models.TimeField(db_column='TO_TIME')),
                ('LATE_COMING_TIME', models.TimeField(db_column='LATE_COMING_TIME')),
                ('EARLY_GOING_TIME', models.TimeField(db_column='EARLY_GOING_TIME')),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', max_length=50)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', max_length=50)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
            ],
            options={
                'db_table': '"ESTABLISHMENT"."SHIFT_MASTER"',
            },
        ),
        migrations.CreateModel(
            name='STATUS_MASTER',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('RECORD_WORD', models.CharField(db_column='RECORD_WORD', max_length=100)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', max_length=50)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', max_length=50)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
            ],
            options={
                'db_table': '"ESTABLISHMENT"."STATUS_MASTER"',
            },
        ),
        migrations.CreateModel(
            name='TYPE_MASTER',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('RECORD_WORD', models.CharField(db_column='RECORD_WORD', max_length=100)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', max_length=50)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', max_length=50)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
            ],
            options={
                'db_table': '"ESTABLISHMENT"."TYPE_MASTER"',
            },
        ),
    ]
