# Generated by Django 4.2.19 on 2025-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift_master',
            options={'verbose_name': 'Shift Master', 'verbose_name_plural': 'Shift Masters'},
        ),
        migrations.AlterModelOptions(
            name='status_master',
            options={'verbose_name': 'Status Master', 'verbose_name_plural': 'Status Masters'},
        ),
        migrations.AlterModelOptions(
            name='type_master',
            options={'verbose_name': 'Type Master', 'verbose_name_plural': 'Type Masters'},
        ),
        migrations.AddField(
            model_name='shift_master',
            name='DELETED_AT',
            field=models.DateTimeField(blank=True, db_column='DELETED_AT', null=True),
        ),
        migrations.AddField(
            model_name='shift_master',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status_master',
            name='DELETED_AT',
            field=models.DateTimeField(blank=True, db_column='DELETED_AT', null=True),
        ),
        migrations.AddField(
            model_name='status_master',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='type_master',
            name='DELETED_AT',
            field=models.DateTimeField(blank=True, db_column='DELETED_AT', null=True),
        ),
        migrations.AddField(
            model_name='type_master',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shift_master',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shift_master',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status_master',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status_master',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='type_master',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='type_master',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
    ]
