# Generated by Django 4.2.19 on 2025-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_alter_shift_master_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_master',
            name='EARLY_GOING_TIME',
            field=models.TimeField(blank=True, db_column='EARLY_GOING_TIME', null=True),
        ),
        migrations.AlterField(
            model_name='shift_master',
            name='LATE_COMING_TIME',
            field=models.TimeField(blank=True, db_column='LATE_COMING_TIME', null=True),
        ),
    ]
