# Generated by Django 4.2.19 on 2025-02-20 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('STUDENT_ID', models.AutoField(db_column='STUDENT_ID', primary_key=True, serialize=False)),
                ('ENROLLMENT_NO', models.CharField(db_column='ENROLLMENT_NO', max_length=20, unique=True)),
                ('FIRST_NAME', models.CharField(db_column='FIRST_NAME', max_length=50)),
                ('MIDDLE_NAME', models.CharField(blank=True, db_column='MIDDLE_NAME', max_length=50, null=True)),
                ('LAST_NAME', models.CharField(db_column='LAST_NAME', max_length=50)),
                ('DATE_OF_BIRTH', models.DateField(db_column='DATE_OF_BIRTH')),
                ('GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_column='GENDER', max_length=1)),
                ('EMAIL', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('PHONE', models.CharField(db_column='PHONE', max_length=15)),
                ('ADDRESS', models.TextField(db_column='ADDRESS')),
                ('CITY', models.CharField(db_column='CITY', max_length=50)),
                ('STATE', models.CharField(db_column='STATE', max_length=50)),
                ('PINCODE', models.CharField(db_column='PINCODE', max_length=6)),
                ('BLOOD_GROUP', models.CharField(db_column='BLOOD_GROUP', max_length=5)),
                ('PHOTO', models.ImageField(blank=True, db_column='PHOTO', null=True, upload_to='student_photos/')),
                ('CURRENT_SEMESTER', models.IntegerField(db_column='CURRENT_SEMESTER')),
                ('ADMISSION_DATE', models.DateField(db_column='ADMISSION_DATE')),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('ACADEMIC_YEAR', models.ForeignKey(db_column='ACADEMIC_YEAR_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.academic_year')),
                ('BRANCH', models.ForeignKey(db_column='BRANCH_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('CREATED_BY', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('DELETED_BY', models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('PROGRAM', models.ForeignKey(db_column='PROGRAM_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.program')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': '"STUDENT"."STUDENTS"',
            },
        ),
        migrations.CreateModel(
            name='STUDENT_RESULT',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RESULT_ID', models.AutoField(db_column='RESULT_ID', primary_key=True, serialize=False)),
                ('MARKS_OBTAINED', models.DecimalField(db_column='MARKS_OBTAINED', decimal_places=2, max_digits=5)),
                ('IS_PASS', models.BooleanField(db_column='IS_PASS')),
                ('GRADE', models.CharField(db_column='GRADE', max_length=2)),
                ('GRADE_POINTS', models.DecimalField(db_column='GRADE_POINTS', decimal_places=1, max_digits=3)),
                ('ATTEMPT_NUMBER', models.IntegerField(db_column='ATTEMPT_NUMBER', default=1)),
                ('REMARKS', models.CharField(blank=True, db_column='REMARKS', max_length=255, null=True)),
                ('IS_VERIFIED', models.BooleanField(db_column='IS_VERIFIED', default=False)),
                ('CREATED_BY', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('CURRICULUM', models.ForeignKey(db_column='CURRICULUM_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.curriculum')),
                ('DELETED_BY', models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('EXAMINATION', models.ForeignKey(db_column='EXAMINATION_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.examination')),
                ('STUDENT', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
                'db_table': '"STUDENT"."STUDENT_RESULTS"',
                'unique_together': {('STUDENT', 'CURRICULUM', 'EXAMINATION', 'ATTEMPT_NUMBER')},
            },
        ),
        migrations.CreateModel(
            name='STUDENT_PARENT',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('PARENT_ID', models.AutoField(db_column='PARENT_ID', primary_key=True, serialize=False)),
                ('RELATION', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian')], db_column='RELATION', max_length=10)),
                ('FIRST_NAME', models.CharField(db_column='FIRST_NAME', max_length=50)),
                ('MIDDLE_NAME', models.CharField(blank=True, db_column='MIDDLE_NAME', max_length=50, null=True)),
                ('LAST_NAME', models.CharField(db_column='LAST_NAME', max_length=50)),
                ('OCCUPATION', models.CharField(db_column='OCCUPATION', max_length=100)),
                ('EMAIL', models.EmailField(db_column='EMAIL', max_length=254)),
                ('PHONE', models.CharField(db_column='PHONE', max_length=15)),
                ('ANNUAL_INCOME', models.DecimalField(db_column='ANNUAL_INCOME', decimal_places=2, max_digits=12)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('CREATED_BY', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('DELETED_BY', models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('STUDENT', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Parent',
                'verbose_name_plural': 'Student Parents',
                'db_table': '"STUDENT"."STUDENT_PARENTS"',
                'unique_together': {('STUDENT', 'RELATION')},
            },
        ),
        migrations.CreateModel(
            name='STUDENT_ACADEMIC',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('ACADEMIC_ID', models.AutoField(db_column='ACADEMIC_ID', primary_key=True, serialize=False)),
                ('QUALIFICATION', models.CharField(db_column='QUALIFICATION', max_length=50)),
                ('BOARD_UNIVERSITY', models.CharField(db_column='BOARD_UNIVERSITY', max_length=100)),
                ('INSTITUTION', models.CharField(db_column='INSTITUTION', max_length=200)),
                ('YEAR_OF_PASSING', models.IntegerField(db_column='YEAR_OF_PASSING')),
                ('PERCENTAGE', models.DecimalField(db_column='PERCENTAGE', decimal_places=2, max_digits=5)),
                ('DIVISION', models.CharField(db_column='DIVISION', max_length=20)),
                ('SUBJECTS', models.JSONField(db_column='SUBJECTS')),
                ('DOCUMENTS', models.JSONField(blank=True, db_column='DOCUMENTS', null=True)),
                ('IS_VERIFIED', models.BooleanField(db_column='IS_VERIFIED', default=False)),
                ('CREATED_BY', models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('DELETED_BY', models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('STUDENT', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Academic',
                'verbose_name_plural': 'Student Academics',
                'db_table': '"STUDENT"."STUDENT_ACADEMICS"',
                'unique_together': {('STUDENT', 'QUALIFICATION')},
            },
        ),
    ]
