# Generated by Django 4.2.19 on 2025-02-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACADEMIC_TERM',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('ACADEMIC_TERM_ID', models.AutoField(db_column='ACADEMIC_TERM_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=50)),
                ('CODE', models.CharField(db_column='CODE', max_length=20)),
                ('START_DATE', models.DateField(db_column='START_DATE')),
                ('END_DATE', models.DateField(db_column='END_DATE')),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'db_table': '"ACADEMIC"."ACADEMIC_TERMS"',
            },
        ),
        migrations.CreateModel(
            name='ACADEMIC_YEAR',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('ACADEMIC_YEAR_ID', models.AutoField(db_column='ACADEMIC_YEAR_ID', primary_key=True, serialize=False)),
                ('YEAR', models.CharField(db_column='YEAR', max_length=9, unique=True)),
                ('START_DATE', models.DateField(db_column='START_DATE')),
                ('END_DATE', models.DateField(db_column='END_DATE')),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': '"ACADEMIC"."ACADEMIC_YEARS"',
            },
        ),
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('COURSE_ID', models.AutoField(db_column='COURSE_ID', primary_key=True, serialize=False)),
                ('CODE', models.CharField(db_column='CODE', max_length=20, unique=True)),
                ('NAME', models.CharField(db_column='NAME', max_length=255)),
                ('DESCRIPTION', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('CREDITS', models.DecimalField(db_column='CREDITS', decimal_places=2, max_digits=4)),
                ('LECTURE_HOURS', models.IntegerField(db_column='LECTURE_HOURS')),
                ('LAB_HOURS', models.IntegerField(db_column='LAB_HOURS', default=0)),
                ('TUTORIAL_HOURS', models.IntegerField(db_column='TUTORIAL_HOURS', default=0)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': '"ACADEMIC"."COURSES"',
            },
        ),
        migrations.CreateModel(
            name='CURRICULUM',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('CURRICULUM_ID', models.AutoField(db_column='CURRICULUM_ID', primary_key=True, serialize=False)),
                ('SEMESTER', models.IntegerField(db_column='SEMESTER')),
                ('IS_ELECTIVE', models.BooleanField(db_column='IS_ELECTIVE', default=False)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'db_table': '"ACADEMIC"."CURRICULUM"',
            },
        ),
        migrations.CreateModel(
            name='EXAMINATION',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('EXAMINATION_ID', models.AutoField(db_column='EXAMINATION_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=255)),
                ('CODE', models.CharField(db_column='CODE', max_length=20, unique=True)),
                ('EXAM_TYPE', models.CharField(choices=[('INTERNAL', 'Internal Assessment'), ('MIDTERM', 'Mid Term'), ('ENDTERM', 'End Term'), ('PRACTICAL', 'Practical'), ('VIVA', 'Viva Voce')], db_column='EXAM_TYPE', max_length=20)),
                ('START_DATE', models.DateField(db_column='START_DATE')),
                ('END_DATE', models.DateField(db_column='END_DATE')),
                ('MAX_MARKS', models.DecimalField(db_column='MAX_MARKS', decimal_places=2, max_digits=5)),
                ('PASSING_MARKS', models.DecimalField(db_column='PASSING_MARKS', decimal_places=2, max_digits=5)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('ACADEMIC_TERM', models.ForeignKey(db_column='ACADEMIC_TERM_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.academic_term')),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'db_table': '"ACADEMIC"."EXAMINATIONS"',
            },
        ),
    ]
