# Generated by Django 4.2.19 on 2025-02-20 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='CREATED_BY',
            field=models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='DELETED_BY',
            field=models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examination',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='ACADEMIC_YEAR',
            field=models.ForeignKey(db_column='ACADEMIC_YEAR_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.academic_year'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='BRANCH',
            field=models.ForeignKey(db_column='BRANCH_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='COURSE',
            field=models.ForeignKey(db_column='COURSE_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='CREATED_BY',
            field=models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='DELETED_BY',
            field=models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='PROGRAM',
            field=models.ForeignKey(db_column='PROGRAM_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.program'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='CREATED_BY',
            field=models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='DELETED_BY',
            field=models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='CREATED_BY',
            field=models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='DELETED_BY',
            field=models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_term',
            name='ACADEMIC_YEAR',
            field=models.ForeignKey(db_column='ACADEMIC_YEAR_ID', on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academic.academic_year'),
        ),
        migrations.AddField(
            model_name='academic_term',
            name='CREATED_BY',
            field=models.ForeignKey(blank=True, db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_term',
            name='DELETED_BY',
            field=models.ForeignKey(blank=True, db_column='DELETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academic_term',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('BRANCH', 'PROGRAM', 'ACADEMIC_YEAR', 'COURSE', 'SEMESTER')},
        ),
        migrations.AlterUniqueTogether(
            name='academic_term',
            unique_together={('ACADEMIC_YEAR', 'CODE')},
        ),
    ]
