# Generated by Django 4.2.19 on 2025-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_term',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_term',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_term',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='CREATED_BY',
            field=models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='DELETED_BY',
            field=models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='UPDATED_BY',
            field=models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True),
        ),
    ]
